### ISSUE TITLE
Why the "/log/" folder is empty?

### ISSUE THREAD

**Issue by ZeyuanYu** [lukasruff/Deep-SVDD-PyTorch#5]
It requires "log.txt", "result.json", "model.tar" such files and so on.
But how could I get these files to fill the "/log/" folder?
There is no related content in "Readme.md". So now I'm really confused.
Thanks.

**Comment by lukasruff** [comment]
Those files are the output from running an experiment.

You can specify the export path by the `xp_path` argument (3rd argument) of the `main.py` script.

Have you tried running the MNIST example?

```python main.py mnist mnist_LeNet ../log/mnist_test ../data --objective one-class --lr 0.0001 --n_epochs 150 --lr_milestone 50 --batch_size 200 --weight_decay 0.5e-6 --pretrain True --ae_lr 0.0001 --ae_n_epochs 150 --ae_lr_milestone 50 --ae_batch_size 200 --ae_weight_decay 0.5e-3 --normal_class 3;```


You can use the `--load_config` or the `--load_model` option to either load an experimental configuration or a model from the respective files (`config.json` or `model.tar`) afterwards.
`log.txt` is a log-file of the console prints and `result.json` contains the results of an experiment.

**Comment by peiseng** [comment]
Create a blank folder named "mnist_test" inside the "log" folder. As when you configure the path to "../log/mnist_test", the folder named "mnist_test" does not exit leading to error.

**Comment by lukasruff** [comment]
I've updated the examples in README for clarity.
